### ISSUE TITLE
Is Raphy Charts project dead?

### ISSUE THREAD

**Issue by andythenorth** [jcarver989/raphy-charts#20]
Sorry for asking this question in an issue :)

Dead link at http://softwarebyjosh.com/raphy-charts 
Couldn't find much to suggest the project is still alive (no recent commits, not many forks or pull requests, no twitter etc) :)  

Want to use Raphy Charts as it looks like a great alternative to g.raphael which is very limited.  Wondering whether or not to fork and maintain our own version...

**Comment by jcarver989** [comment]
Yea - I've long since stopped maintaining this repository. A lot has changed in front-end land since I started Raphy Charts. If you're looking for a successor to Raphy Charts, that's easy to use, gives responsive charts etc checkout my current project: https://github.com/jcarver989/suave-charts
